Repository omise/omise-magento, pull requests merged in 2018-10, with the labels that each got.

#157 Update README.md
  README.md
Labels: project: 2.x, status: Ready

#156 Fixes issue with orders not being updated after an order 'cancelled' by closing browser tab/window
  src/app/code/community/Omise/Gateway/Model/Event/Charge/Complete.php
  src/app/code/community/Omise/Gateway/Model/Order.php
Labels: project: 1.x, status: Review needed

#160 Fixed problem that translation to 'Select a card you want to proceed'
  view/frontend/web/template/payment/omise-cc-form.html
Labels: project: 2.x, status: Ready

#161 Restrict internet banking payment method to THB orders only
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-internetbanking-method.js
  view/frontend/web/template/payment/offsite-internetbanking-form.html
Labels: project: 2.x, status: Review needed
