Repository omise/omise-magento, pull requests merged in 2018-09, with the labels that each got.

#149 Offsite refactoring, changed Offsite names to APM
  Controller/Callback/Offsite.php
  Gateway/Request/APMBuilder.php
  Gateway/Request/CreditCardAuthorizeBuilder.php
  Gateway/Request/CreditCardAuthorizeCaptureBuilder.php
  Gateway/Request/CreditCardThreeDSecureBuilder.php
  Gateway/Validator/OmiseAPMInitializeCommandResponseValidator.php
  Model/Config/Alipay.php
  Model/Config/Internetbanking.php
  Observer/InternetbankingDataAssignObserver.php
  etc/config.xml
  etc/di.xml
  etc/events.xml
Labels: project: 2.x, status: Ready

#150 Mitigate issue caused by multiple hits on `return_uri`
  src/app/code/community/Omise/Gateway/Model/Order.php
  src/app/code/community/Omise/Gateway/controllers/Callback/ValidateoffsitealipayController.php
  src/app/code/community/Omise/Gateway/controllers/Callback/ValidateoffsiteinternetbankingController.php
  src/app/code/community/Omise/Gateway/controllers/Callback/ValidatethreedsecureController.php
Labels: project: 1.x, status: Review needed

#123 MAG2x: Add a capability to remember user's credit card and use it for a second-time purchase
  Gateway/Request/CreditCardBuilder.php
  Model/Api/Customer.php
  Model/Customer.php
  Model/Ui/CcConfigProvider.php
  Observer/CreditCardDataObserver.php
  Setup/UpgradeData.php
  view/frontend/web/js/view/payment/method-renderer/omise-cc-method.js
  view/frontend/web/template/payment/omise-cc-form.html
Labels: project: 2.x, status: Ready

#153 MAG2x: Changing long array syntax to the short syntax one.
  Controller/Callback/Offsite.php
  Model/Api/Customer.php
  Model/Api/Error.php
  Model/Customer.php
  Model/Ui/CcConfigProvider.php
  Test/Unit/Model/Api/ObjectTest.php
Labels: project: 2.x, status: Ready

#140 Tesco Lotus Payment Implementation
  Block/Checkout/Onepage/Success/TescoAdditionalInformation.php
  Gateway/Request/APMBuilder.php
  Gateway/Response/PaymentDetailsHandler.php
  Model/Config/Tesco.php
  etc/adminhtml/system.xml
  etc/config.xml
  etc/di.xml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/layout/checkout_onepage_success.xml
  view/frontend/templates/checkout/onepage/success/tesco_additional_info.phtml
  view/frontend/web/js/view/payment/method-renderer/omise-offline-tesco-method.js
  view/frontend/web/js/view/payment/omise.js
  view/frontend/web/template/payment/offline-tesco-form.html
Labels: project: 2.x, status: Review needed

#155 change plugin version from 2.4.0-dev to 2.4.0 - to release
  composer.json
Labels: project: 2.x, status: Ready
