Repository omise/omise-magento, pull requests merged in 2019-07, with the labels that each got.

#201 True Money Payment Method Implementation
  CHANGELOG.md
  Controller/Callback/Offsite.php
  Gateway/Request/APMBuilder.php
  Model/Config/Truemoney.php
  etc/adminhtml/system.xml
  etc/config.xml
  etc/di.xml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-truemoney-method.js
  view/frontend/web/js/view/payment/omise.js
  view/frontend/web/template/payment/offsite-truemoney-form.html
Labels: project: 2.x, status: Ready

#205 Change to display an error message using ErrorMessageMapper
  Gateway/Validator/OmiseAuthorizeCommandResponseValidator.php
  Gateway/Validator/OmiseCaptureCommandResponseValidator.php
  etc/di.xml
  etc/omise_error_mapping.xml
Labels: project: 2.x, status: Review needed

#207 Edit phone number on checkout-page when making True Money payment
  Gateway/Request/APMBuilder.php
  Observer/TruemoneyDataAssignObserver.php
  etc/events.xml
  view/frontend/web/css/styles.css
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-truemoney-method.js
  view/frontend/web/template/payment/offsite-truemoney-form.html
Labels: project: 2.x, status: Review needed

#208 2.8 Release Preparation
  CHANGELOG.md
  composer.json
  etc/module.xml
Labels: project: 2.x, status: Review needed

#209 Update README.md
  README.md
Labels: project: 2.x, status: Review needed

#213 Too many parameters are sent to parent class in DeleteAction - fix
  Controller/Cards/DeleteAction.php
Labels: project: 2.x, status: Review needed, type: Bug
