Repository omise/omise-magento, pull requests merged in 2019-05, with the labels that each got.

#188 Change minimum order from 5000 to 3000 THB
  i18n/th_TH.csv
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-installment-method.js
  view/frontend/web/template/payment/offsite-installment-form.html
Labels: project: 2.x, status: Review needed

#186 Delete Saved Credit Card Information
  Block/Customer/Cards.php
  Controller/Cards/DeleteAction.php
  Controller/Cards/ListAction.php
  Model/Customer.php
  view/frontend/layout/checkout_onepage_success.xml
  view/frontend/layout/customer_account.xml
  view/frontend/layout/omise_cards_listaction.xml
  view/frontend/templates/cards.phtml
  view/frontend/web/js/view/payment/omise.js
Labels: project: 2.x, status: Review needed

#182 Manual Capture Functionality
  Gateway/Http/Client/APMPayment.php
  Gateway/Http/Client/AbstractPayment.php
  Gateway/Http/Client/CCPayment.php
  Gateway/Request/CreditCardBuilder.php
  Observer/CreditCardDataObserver.php
  etc/di.xml
Labels: project: 2.x, status: Review needed

#191 Refactoring - removed unnecessary redirections
  Controller/Cards/DeleteAction.php
Labels: project: 2.x, status: Review needed

#192 Update Omise-PHP lib v2.11.2 (according to the change of Installment minimum amount)
  src/lib/omise-php/CHANGELOG.md
  src/lib/omise-php/README.md
  src/lib/omise-php/lib/omise/OmiseCapabilities.php
  src/lib/omise-php/lib/omise/res/OmiseApiResource.php
  src/lib/omise-php/test.php
Labels: project: 1.x, status: Ready

#190 Show instalment amounts, interest rates, and enforce monthly and overall minimum payments
  CHANGELOG.md
  src/app/code/community/Omise/Gateway/Block/Form/Offsiteinstallment.php
  src/app/code/community/Omise/Gateway/Helper/Data.php
  src/app/code/community/Omise/Gateway/Model/Api/Capabilities.php
  src/app/code/community/Omise/Gateway/Model/Config.php
  src/app/code/community/Omise/Gateway/etc/config.xml
  src/app/code/community/Omise/Gateway/etc/system.xml
  src/app/design/frontend/base/default/template/payment/form/omise/omiseoffsiteinstallment.phtml
Labels: project: 1.x, status: Review needed

#194 Prep release 1.17
  CHANGELOG.md
  README.md
  src/app/code/community/Omise/Gateway/Model/Omise.php
  src/app/code/community/Omise/Gateway/etc/config.xml
Labels: project: 1.x, status: Review needed

#195 Fix for unable to select some installment terms
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-installment-method.js
  view/frontend/web/template/payment/offsite-installment-form.html
Labels: project: 2.x, status: Review needed

#197 Manage cards link on checkout page
  i18n/th_TH.csv
  view/frontend/web/template/payment/omise-cc-form.html
Labels: project: 2.x, status: Review needed

#199 Add a very visible 'Omise test mode' reminder on the checkout page
  src/app/code/community/Omise/Gateway/Helper/Data.php
  src/app/design/frontend/base/default/layout/omise/gateway.xml
  src/skin/frontend/base/default/omise/gateway/css/style.css
  src/skin/frontend/base/default/omise/gateway/js/testmode.js
Labels: project: 1.x, status: Review needed

#198 Display info on checkout if plugin is in Sandbox mode
  Model/Ui/PluginConfigProvider.php
  etc/frontend/di.xml
  i18n/th_TH.csv
  view/frontend/web/js/view/payment/method-renderer/omise-cc-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offline-tesco-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-alipay-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-installment-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-internetbanking-method.js
  view/frontend/web/template/payment/offline-tesco-form.html
  view/frontend/web/template/payment/offsite-alipay-form.html
  view/frontend/web/template/payment/offsite-installment-form.html
  view/frontend/web/template/payment/offsite-internetbanking-form.html
  view/frontend/web/template/payment/omise-cc-form.html
Labels: project: 2.x, status: Review needed
