Repository omise/omise-magento, pull requests merged in 2019-01, with the labels that each got.

#148 Instalment Payment Option Implementation
  Controller/Callback/Offsite.php
  Gateway/Request/APMBuilder.php
  Model/Api/Capabilities.php
  Model/Capabilities.php
  Model/Config/Installment.php
  Model/Ui/CapabilitiesConfigProvider.php
  Observer/InstallmentDataAssignObserver.php
  composer.json
  etc/adminhtml/system.xml
  etc/config.xml
  etc/di.xml
  etc/events.xml
  etc/frontend/di.xml
  i18n/th_TH.csv
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/css/offsite-internetbanking.css
  view/frontend/web/css/styles.css
  view/frontend/web/images/fc.svg
  view/frontend/web/images/kbank.svg
  view/frontend/web/images/ktc.svg
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-installment-method.js
  view/frontend/web/js/view/payment/omise.js
  view/frontend/web/template/payment/offsite-installment-form.html
Labels: project: 2.x, status: Review needed

#170 Required changes for upcoming 2.5 release
  CHANGELOG.md
  Model/Omise.php
  README.md
  composer.json
  etc/module.xml
Labels: project: 2.x, status: Review needed

#172 Updated CHANGELOG for upcoming 2.5 release
  CHANGELOG.md
Labels: project: 2.x, status: Review needed

#174 Model\Ui\CapabilitiesConfigProvider: returns an empty array instaed o…
  Model/Ui/CapabilitiesConfigProvider.php
Labels: project: 2.x, status: Review needed, type: Bug

#175 Update Changelog, and plugin version for upcoming 2.6 release
  CHANGELOG.md
  composer.json
  etc/module.xml
Labels: project: 2.x, status: Ready

#179 Fix: Order can't be completed when choosing other payment methods than Omise
  Observer/TescoPaymentObserver.php
Labels: project: 2.x, status: Review needed

#180 Fix: Display correctly barcode from tesco lotus on checkout success page.
  Block/Checkout/Onepage/Success/TescoAdditionalInformation.php
  view/frontend/templates/checkout/onepage/success/tesco_additional_info.phtml
Labels: project: 2.x, status: Review needed

#177 Changed in composer omise-php requirement to version 2.11.1
  composer.json
Labels: project: 2.x, status: Review needed

#181 Preparation for 2.7 release
  CHANGELOG.md
  composer.json
  etc/module.xml
Labels: project: 2.x, status: Review needed

#183 Enable 'Order' button only if installment terms are chosen
  view/frontend/web/template/payment/offsite-installment-form.html
Labels: project: 2.x, status: Review needed
