Repository omise/omise-magento, pull requests merged in 2020-11, with the labels that each got.

#277 Adding billing address information to card payment charge token.
  view/frontend/web/js/view/payment/method-renderer/omise-cc-method.js
Labels: project: 2.x, status: Review needed

#273 Add SCB to Installments
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-installment-method.js
  view/frontend/web/template/payment/offsite-installment-form.html
Labels: status: Review needed

#278 Preparing to release 2.14
  CHANGELOG.md
  composer.json
  etc/module.xml
Labels: project: 2.x, status: In progress

#279 Removing 3DS configuration from backend.
  Gateway/Command/CreditCardStrategyCommand.php
  Gateway/Response/PendingInvoiceHandler.php
  Gateway/Response/PendingPaymentHandler.php
  Gateway/Validator/OmiseAuthorizeCommandResponseValidator.php
  Helper/OmiseHelper.php
  Model/Config/Cc.php
  Model/Ui/CcConfigProvider.php
  etc/adminhtml/system.xml
  etc/di.xml
  view/frontend/web/js/view/payment/method-renderer/omise-cc-method.js
Labels: project: 2.x, status: Ready, type: Enhancement
