Repository omise/omise-magento, pull requests merged in 2020-03, with the labels that each got.

#239 Implementing new payment method - Tesco Bill Payment
  src/app/code/community/Omise/Gateway/Block/Checkout/Tesco.php
  src/app/code/community/Omise/Gateway/Block/Form/Default.php
  src/app/code/community/Omise/Gateway/Helper/Data.php
  src/app/code/community/Omise/Gateway/Model/Payment.php
  src/app/code/community/Omise/Gateway/Model/Payment/Offsitetesco.php
  src/app/code/community/Omise/Gateway/controllers/Callback/ValidateoffsitetescoController.php
  src/app/code/community/Omise/Gateway/controllers/Checkout/TescoController.php
  src/app/code/community/Omise/Gateway/etc/config.xml
  src/app/code/community/Omise/Gateway/etc/system.xml
  src/app/design/frontend/base/default/layout/omise/gateway.xml
  src/app/design/frontend/base/default/template/checkout/omise/success.phtml
  src/app/locale/en_US/template/email/omise/tesco_order_confirmation.html
  src/skin/frontend/base/default/omise/gateway/css/style.css
Labels: project: 1.x, status: Review needed

#241 Prepares for v1.20 release
  CHANGELOG.md
  README.md
  src/app/code/community/Omise/Gateway/Model/Omise.php
  src/app/code/community/Omise/Gateway/etc/config.xml
Labels: project: 1.x, status: Review needed

#242 Prepares for v1.20 release
  CHANGELOG.md
Labels: project: 1.x, status: Review needed

#244 Prepares for v1.21 release
  CHANGELOG.md
  README.md
  src/app/code/community/Omise/Gateway/Model/Omise.php
  src/app/code/community/Omise/Gateway/etc/config.xml
Labels: project: 1.x, status: Review needed

#246 2.10-release preperation
  CHANGELOG.md
  README.md
  composer.json
  etc/module.xml
Labels: project: 2.x, status: Ready

#247 Update CHANGELOG.md for upcoming release
  CHANGELOG.md
Labels: project: 2.x, status: Review needed
