Repository omise/omise-magento, pull requests merged in 2021-09, with the labels that each got.

#307 [FRON-728] Allow minimum 2000 for installment payment method
  composer.json
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-installment-method.js
Labels: type: Enhancement, status: Review needed

#308 Bump version to 2.18.6
  CHANGELOG.md
  composer.json
  etc/module.xml
Labels: type: Enhancement, project: 2.x

#309 [EM-902] Add alipayplus wallets for SG
  Controller/Callback/Offsite.php
  Cron/OrderSyncStatus.php
  Gateway/Request/APMBuilder.php
  Helper/OmiseHelper.php
  Model/Config/Alipayplus.php
  etc/adminhtml/system.xml
  etc/config.xml
  etc/di.xml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-alipaycn-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-alipayhk-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-dana-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-gcash-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-kakaopay-method.js
  view/frontend/web/js/view/payment/method-renderer/omise-offsite-touchngo-method.js
  view/frontend/web/js/view/payment/omise.js
  view/frontend/web/template/payment/offsite-alipayplus-form.html
Labels: type: Enhancement, status: Ready
